ogd10:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/10/datapackage.json
    
ogd17:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/17/datapackage.json

ogd47:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/47/datapackage.json

ogd51:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/51/datapackage.json

ogd61:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/61/datapackage.json

staging_Z:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/staging/datapackage_ZIP.json

staging:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/staging/datapackage_NoZIP.json
