ogd6:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/6/datapackage.json
    
ogd10:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/10/datapackage.json
      type: package
    
ogd17:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/17/datapackage.json
    
ogd25:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/25/datapackage.json

ogd47:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/47/datapackage.json

ogd51:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/51/datapackage.json

ogd56:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/56/datapackage.json
      type: package 
      
ogd61:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/61/datapackage.json
    
ogd84:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/84/datapackage.json

ogd85:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/85/datapackage.json

ogd90:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/90/datapackage.json
    
staging:
  tasks:
    - source: https://www.uvek-gis.admin.ch/BFE/ogd/staging/datapackage.json
      type: package 
