name: ogd47

# Test the OGD47 data in https://www.uvek-gis.admin.ch/BFE/ogd/47/ogd47_vollzugsresultate_pw.csv

on:
  push:
    paths:
      - ogd47/trigger.csv
  pull_request:
    paths:
      - ogd47/trigger.csv
      
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate data
        uses: frictionlessdata/repository@v1
        with:
            inquiry: ogd47
        if: success()
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: 'wm-uvekgis'
          server: 'sftp://pub.uvek-gis.admin.ch'
          ssh_private_key: ${{ secrets.SFTP_PASSWORD }} 
          local_path: '${{ secrets.STAGING_AREA }}ogd47_vollzugsresultate_pw.csv'
          remote_path: 'data/www/www.uvek-gis.admin.ch/htdocs/BFE/ogd/47/ogd47_vollzugsresultate_pw.csv'
          args: '-o ConnectTimeout=5'
