name: ogd47

# Test the OGD47 data in https://www.uvek-gis.admin.ch/BFE/ogd/47/ogd47_vollzugsresultate_pw.csv

on:
  push:
    paths:
      - ogd47/trigger.csv
  pull_request:
    paths:
      - ogd47/trigger.csv
      
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate data
        uses: frictionlessdata/repository@v1
        with:
            inquiry: ogd47
        if: success()
      - name: deploy file
        uses: anvil-solutions/Fast-FTP-Action@2.1.3
        with:
          server: pub.uvek-gis.admin.ch
          username: wm-uvekgis
          password: ${{ secrets.SFTP_PASSWORD }}
          method: sftp
          local_dir: ${{ secrets.STAGING_AREA }}ogd47_vollzugsresultate_pw.csv
          remote_dir: data/www/www.uvek-gis.admin.ch/htdocs/BFE/ogd/47/ogd47_vollzugsresultate_pw.csv
