name: ogd85

# Test the OGD85 data in https://www.uvek-gis.admin.ch/BFE/ogd/85/ogd85_stromlandschaft.csv

on:
  push:
    paths:
      - ogd85/trigger.csv
  pull_request:
    paths:
      - ogd85/trigger.csv
      
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate data
        uses: frictionlessdata/repository@v1
        with:
            inquiry: ogd85
